In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')


In [2]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)
data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255
_, m_train = X_train.shape

In [3]:
Y_train

array([9, 8, 7, ..., 6, 3, 8])

In [4]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [5]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [6]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[9 9 7 ... 9 8 0] [9 8 7 ... 6 3 8]
0.11414634146341464
Iteration:  10
[4 7 7 ... 5 3 3] [9 8 7 ... 6 3 8]
0.20119512195121952
Iteration:  20
[4 6 7 ... 5 8 1] [9 8 7 ... 6 3 8]
0.28039024390243905
Iteration:  30
[4 6 7 ... 5 6 1] [9 8 7 ... 6 3 8]
0.34509756097560973
Iteration:  40
[4 8 7 ... 5 6 1] [9 8 7 ... 6 3 8]
0.4040487804878049
Iteration:  50
[4 8 7 ... 5 6 1] [9 8 7 ... 6 3 8]
0.4586585365853659
Iteration:  60
[4 8 7 ... 5 8 1] [9 8 7 ... 6 3 8]
0.504219512195122
Iteration:  70
[4 8 7 ... 5 8 1] [9 8 7 ... 6 3 8]
0.543829268292683
Iteration:  80
[4 8 7 ... 5 3 1] [9 8 7 ... 6 3 8]
0.576
Iteration:  90
[4 8 7 ... 5 3 1] [9 8 7 ... 6 3 8]
0.6046585365853658
Iteration:  100
[4 8 7 ... 5 5 1] [9 8 7 ... 6 3 8]
0.6286341463414634
Iteration:  110
[4 8 7 ... 5 5 1] [9 8 7 ... 6 3 8]
0.6505121951219512
Iteration:  120
[4 8 7 ... 5 5 1] [9 8 7 ... 6 3 8]
0.6722926829268293
Iteration:  130
[4 8 7 ... 5 5 1] [9 8 7 ... 6 3 8]
0.6900243902439024
Iteration:  140
[4 8 7 ... 5